name: Workflowwow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Service'
        uses: actions/checkout@v4
      - name: 'Setup python'
        uses: actions/setup-python@v5
      - name: 'install all depedencies'
        run: pip install --quiet --upgrade --requirement requirements.txt
      - name: 'Lintage du code'
        run: |
          flake8 --ignore=E501,E231 *.py
	  pylint --errors-only --disable=C0301 --disable=C0326 *.py
